use_format_specific_options: false
default_highlighting: GESHIFILTER_DEFAULT_DONOTHING
default_line_numbering: 0
use_highlight_string_for_php: false
enable_keyword_urls: true
decode_entities: false
css_mode: 2
code_container: '2'
tags: 'code blockcode'
tag_styles:
  16: 16
  1: 0
  2: 0
  4: 0
  8: 0
tab_width: 2
language:
  php:
    enabled: true
    tags: php
  cpp:
    enabled: true
    tags: cpp
  java:
    enabled: true
    tags: java
  javascript:
    enabled: true
    tags: javascript
  text:
    enabled: true
    tags: text
  actionscript:
    enabled: true
    tags: actionscript
  apache:
    enabled: true
    tags: apache
  apt_sources:
    enabled: true
    tags: apt_sources
  bash:
    enabled: true
    tags: bash
  c:
    enabled: true
    tags: c
  cfm:
    enabled: true
    tags: cfm
  clojure:
    enabled: true
    tags: clojure
  cmake:
    enabled: true
    tags: cmake
  coffeescript:
    enabled: true
    tags: coffeescript
  cpp-qt:
    enabled: true
    tags: cpp-qt
  cpp-winapi:
    enabled: true
    tags: cpp-winapi
  csharp:
    enabled: true
    tags: csharp
  css:
    enabled: true
    tags: css
  diff:
    enabled: true
    tags: diff
  ecmascript:
    enabled: true
    tags: ecmascript
  gettext:
    enabled: true
    tags: gettext
  go:
    enabled: true
    tags: go
  haskell:
    enabled: true
    tags: haskell
  html4strict:
    enabled: true
    tags: html4strict
  html5:
    enabled: true
    tags: html5
  j:
    enabled: true
    tags: j
  java5:
    enabled: true
    tags: java5
  jquery:
    enabled: true
    tags: jquery
  make:
    enabled: true
    tags: make
  mathematica:
    enabled: true
    tags: mathematica
  matlab:
    enabled: true
    tags: matlab
  mysql:
    enabled: true
    tags: mysql
  nginx:
    enabled: true
    tags: nginx
  objc:
    enabled: true
    tags: objc
  oracle11:
    enabled: true
    tags: oracle11
  pascal:
    enabled: true
    tags: pascal
  pcre:
    enabled: true
    tags: pcre
  perl:
    enabled: true
    tags: perl
  perl6:
    enabled: true
    tags: perl6
  postgresql:
    enabled: true
    tags: postgresql
  pycon:
    enabled: true
    tags: pycon
  pys60:
    enabled: true
    tags: pys60
  python:
    enabled: true
    tags: python
  rails:
    enabled: true
    tags: rails
  ruby:
    enabled: true
    tags: ruby
  rust:
    enabled: true
    tags: rust
  sass:
    enabled: true
  sql:
    enabled: true
    tags: sql
  twig:
    enabled: true
    tags: twig
  typoscript:
    enabled: true
    tags: typoscript
  vbscript:
    enabled: true
    tags: vbscript
  xml:
    enabled: true
    tags: xml
  yaml:
    enabled: true
    tags: yaml
_core:
  default_config_hash: 1jZtSc2CSiEBA45nbX0wMKFY3bmcilIwOBQCKFscK0U
